/**
 * Arduino Forge — Export API
 *
 * Endpoint to bundle generated code and documentation into a .zip file
 * so users can easily open it in the Arduino IDE.
 */

import express from "express";
import JSZip from "jszip";

const router = express.Router();

// Generate a safe project name from the prompt or use a default
function generateProjectName(prompt) {
    if (!prompt) return "ArduinoForge_Project";

    // Try to extract a meaningful snippet
    const words = prompt.replace(/[^a-zA-Z0-9 ]/g, "").split(" ").filter(Boolean);
    const snippet = words.slice(0, 3).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join("");

    return snippet ? `Forge_${snippet}` : "ArduinoForge_Project";
}

/**
 * POST /api/export
 * Body: { prompt, code, wiring, libraries, notes }
 * Output: application/zip stream
 */
router.post("/", async (req, res) => {
    try {
        const { prompt, code, wiring, libraries, notes } = req.body;

        if (!code) {
            return res.status(400).json({ error: "Code is required to generate a ZIP" });
        }

        const projectName = generateProjectName(prompt);

        // Initialize zip
        const zip = new JSZip();

        // 1. Create the main Arduino structure: ProjectName/ProjectName.ino
        // The folder name must strictly match the .ino file name for the Arduino IDE
        const projectFolder = zip.folder(projectName);

        // Add the C++ code
        projectFolder.file(`${projectName}.ino`, code);

        // 2. Generate a comprehensive README.md
        let readme = `# ${projectName}\n\n`;
        readme += `> Generated by [Arduino Forge](https://github.com/SKar-2007/arduino-forge)\n\n`;

        if (prompt) {
            readme += `## Project Goal\n${prompt}\n\n`;
        }

        if (libraries && libraries.length > 0) {
            readme += `## Required Libraries\n`;
            readme += `Install these via **Sketch > Include Library > Manage Libraries** in the Arduino IDE:\n`;
            libraries.forEach(lib => {
                readme += `- \`${lib}\`\n`;
            });
            readme += `\n`;
        }

        if (wiring) {
            readme += `## Hardware Schematics (Wiring)\n`;
            readme += "```text\n" + wiring + "\n```\n\n";
        }

        if (notes) {
            readme += `## Additional Notes\n${notes}\n`;
        }

        projectFolder.file("README.md", readme);

        // Generate the zip buffer
        const zipBuffer = await zip.generateAsync({
            type: "nodebuffer",
            compression: "DEFLATE",
            compressionOptions: { level: 6 }
        });

        // Send response
        res.set("Content-Type", "application/zip");
        res.set("Content-Disposition", `attachment; filename="${projectName}.zip"`);
        res.set("Content-Length", zipBuffer.length);
        res.send(zipBuffer);

    } catch (err) {
        console.error("[export] Error generating ZIP:", err);
        res.status(500).json({ error: "Failed to generate ZIP file" });
    }
});

export default router;
