import express from "express";
import JSZip from "jszip";
import { logger } from "../utils/logger.js";

const router = express.Router();

function generateProjectName(prompt) {
  if (!prompt) return "ArduinoForge_Project";
  const words = prompt.replace(/[^a-zA-Z0-9 ]/g, "").split(" ").filter(Boolean);
  const snippet = words.slice(0, 3).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join("");
  return snippet ? `Forge_${snippet}` : "ArduinoForge_Project";
}

router.post("/", async (req, res) => {
  try {
    const { prompt, code, wiring, libraries, notes, format } = req.body;
    if (!code) {
      return res.status(400).json({ error: "Code is required to generate a ZIP" });
    }

    const projectName = generateProjectName(prompt);
    const zip = new JSZip();

    if (format === "platformio") {
      const srcFolder = zip.folder(`${projectName}/src`);
      srcFolder.file("main.cpp", code);

      const libDeps = libraries?.length
        ? libraries.map(l => `  ${l}`).join("\n")
        : "";

      zip.file(`${projectName}/platformio.ini`, `[env:${req.body.board || "uno"}]
platform = atmelavr
board = ${req.body.board || "uno"}
framework = arduino
lib_deps =${libDeps}
`);
      zip.file(`${projectName}/README.md`, `# ${projectName}\n\nGenerated by Arduino Forge\n`);
    } else {
      const projectFolder = zip.folder(projectName);
      projectFolder.file(`${projectName}.ino`, code);

      let readme = `# ${projectName}\n\n> Generated by [Arduino Forge](https://github.com/SKar-2007/arduino-forge)\n\n`;
      if (prompt) readme += `## Project Goal\n${prompt}\n\n`;
      if (libraries?.length > 0) {
        readme += `## Required Libraries\nInstall these via **Sketch > Include Library > Manage Libraries**:\n`;
        libraries.forEach(lib => { readme += `- \`${lib}\`\n`; });
        readme += `\n`;
      }
      if (wiring) readme += `## Hardware Schematics (Wiring)\n\`\`\`text\n${wiring}\n\`\`\`\n\n`;
      if (notes) readme += `## Additional Notes\n${notes}\n`;

      projectFolder.file("README.md", readme);
    }

    const zipBuffer = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    res.set("Content-Type", "application/zip");
    res.set("Content-Disposition", `attachment; filename="${projectName}.zip"`);
    res.set("Content-Length", zipBuffer.length);
    res.send(zipBuffer);
  } catch (err) {
    logger.error({ err }, "Export failed");
    res.status(500).json({ error: "Failed to generate ZIP file" });
  }
});

export default router;
